package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.models.*;
import org.junit.jupiter.api.*;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.NoSuchElementException;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DAOBeneficiaryTest {
    public static Beneficiary b1;
    public static Beneficiary b2;
    public static Beneficiary b3;
    public final static DAOBeneficiary beneficiaryDAO = new DAOBeneficiary();

    @BeforeAll
    public static void init() throws SQLException {
        DatabaseConnector.initialize("login", "password");
        City c1 = new City(1, "Bruxelles", 1000);
        new DAOCity().create(c1);
        Location l1 = new Location(1, "Bruxelles", c1, "Rue Neuve", "5", 0);
        new DAOLocation().create(l1);
        Interpreter i1 = new Interpreter(1, "b741985", "Alice", "Charpentier", LocalDate.now().minusYears(25),
                "yth794t8rg", "alice@gmail.com", "4865/75.98.24", 20, 300,
                "Vélo", new HashSet<>(), new HashSet<>(), l1, new HashSet<>());
        new DAOInterpreter().create(i1);

        Status s1 = new Status(1, "Test", 50);
        new DAOStatus().create(s1);

        b1 = new Beneficiary(75, "test1", "Toto", "Toto", LocalDate.now().minusYears(10),
                "1234", "toto@gmail.com", "123/45.67.89", s1, i1);
        b2 = new Beneficiary(2, "r260001", "Tata", "Tata", LocalDate.now().minusYears(15),
                "9874", "tata@gmail.com", "987/65.41.32", s1, i1);
        b3 = new Beneficiary(4, "i412876", "Jessica", "DuBuisson", LocalDate.now().minusYears(7),
                "greg54re1fe", "jessica@gmail.com", "754/69.24.18", s1, i1);
    }

    @AfterAll
    public static void close() throws SQLException {
        resetAll();
        DatabaseConnector.closeInstance();
    }

    /*
     * Reset the tables used.
     */
    private static void resetAll() throws SQLException {
        String query1 = "DELETE FROM AppliUserT";
        String query2 = "ALTER TABLE AppliUserT MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query3 = "DELETE FROM Status";
        String query4 = "ALTER TABLE Status MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query5 = "DELETE FROM Location";
        String query6 = "ALTER TABLE Location MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query7 = "DELETE FROM City";
        String query8 = "ALTER TABLE City MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        PreparedStatement statement = null;

        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query1);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query2);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query3);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query4);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query5);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query6);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query7);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query8);
            statement.executeQuery();

        } finally {
            if(statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Test
    @Order(4)
    public void testFind() throws SQLException {
        Beneficiary b4 = beneficiaryDAO.find(2);
        assertEquals(b3, b4, "Find the updated object.");
        assertNotEquals(b3.getLogin(), b4.getLogin(), "The login must not have been updated.");
        assertEquals(b2, beneficiaryDAO.find(3), "Find the unchanged object.");
        assertNull(beneficiaryDAO.find(4), "There is no object with this ID.");
    }

    @Test
    @Order(1)
    public void testCreate() {
        assertDoesNotThrow(() -> {
            beneficiaryDAO.create(b1);
        }, "Create a object in the database.");
        assertEquals(2, b1.getId(), "The ID must have been changed.");
        assertEquals("b260002", b1.getLogin(), "The login must have been changed.");

        b1.setId(20);
        assertThrows(AlreadyExistsException.class, () -> {
            beneficiaryDAO.create(b1);
        }, "This object already exists in the database with another ID.");

        assertDoesNotThrow(() -> {
            beneficiaryDAO.create(b2);
        }, "Create another object in the database.");
        assertEquals(3, b2.getId(), "The ID must have been changed.");
        assertEquals("b260003", b2.getLogin(), "The login must have been changed.");
    }

    @Test
    @Order(3)
    public void testUpdate() {
        assertThrows(NoSuchElementException.class, () -> {
            beneficiaryDAO.update(b3);
        }, "There are no objects with this ID.");

        b3.setId(2);
        assertDoesNotThrow(() -> {
            beneficiaryDAO.update(b3);
        }, "The object has been updated.");

        b3.setId(3);
        assertThrows(AlreadyExistsException.class, () -> {
            beneficiaryDAO.update(b3);
        }, "This object already exists in the database with another ID.");
    }

    @Test
    @Order(5)
    public void testDelete() {
        assertDoesNotThrow(() -> {
            beneficiaryDAO.delete(b2.getId());
        }, "The object has been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            beneficiaryDAO.delete(b2.getId());
        }, "The object has already been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            beneficiaryDAO.delete(50);
        }, "There is no object with this ID.");

        assertDoesNotThrow(() -> {
            beneficiaryDAO.delete(2);
        }, "The object has been removed from the database.");
    }

    @Test
    @Order(2)
    public void testFindAll() throws SQLException {
        Set<Beneficiary> beneficiaries = beneficiaryDAO.findAll();
        assertEquals(2, beneficiaries.size(), "There are two objects in the database.");
        assertTrue(beneficiaries.contains(b1));
        assertTrue(beneficiaries.contains(b2));
    }
}