package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.models.*;
import org.junit.jupiter.api.*;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.NoSuchElementException;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DAOExceptionalUnavailabilityTest {
    public static ExceptionalUnavailability u1;
    public static ExceptionalUnavailability u2;
    public static ExceptionalUnavailability u3;
    public static Interpreter i1;
    public static Interpreter i2;
    public final static DAOExceptionalUnavailability unavailabilityDAO = new DAOExceptionalUnavailability();
    public final static LocalDateTime today = LocalDateTime.now();

    @BeforeAll
    public static void init() throws SQLException {
        DatabaseConnector.initialize();
        City c1 = new City(1, "Bruxelles", 1000);
        new DAOCity().create(c1);
        Location l1 = new Location(1, "Bruxelles", c1, "Rue Neuve", "5", 0);
        new DAOLocation().create(l1);
        i1 = new Interpreter(1, "test1", "Toto", "Toto", LocalDate.now().minusYears(30),
                "1234", "toto@gmail.com", "123/45.67.89", 10, 120,
                "Auto", new HashSet<>(), new HashSet<>(), l1, new HashSet<>());
        i2 = new Interpreter(2, "i260001", "Tata", "Tata", LocalDate.now().minusYears(50),
                "9874", "tata@gmail.com", "987/65.41.32", 30, 450,
                "Auto", new HashSet<>(), new HashSet<>(), l1, new HashSet<>());
        new DAOInterpreter().create(i1);
        new DAOInterpreter().create(i2);

        PunctualTimeSlot p1 = new PunctualTimeSlot(1, today.plusWeeks(1), today.plusWeeks(2));
        PunctualTimeSlot p2 = new PunctualTimeSlot(2, today.minusDays(3), today.plusDays(2));
        new DAOPunctualTimeSlot().create(p1);
        new DAOPunctualTimeSlot().create(p2);

        u1 = new ExceptionalUnavailability("Sick", p1);
        u2 = new ExceptionalUnavailability("Party", p2);
        u3 = new ExceptionalUnavailability("Vacancy", p1);
    }

    @AfterAll
    public static void close() throws SQLException {
        resetAll();
        DatabaseConnector.closeInstance();
    }

    /*
     * Reset the tables used.
     */
    private static void resetAll() throws SQLException {
        String query1 = "DELETE FROM TimeSlot";
        String query2 = "ALTER TABLE TimeSlot MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query3 = "DELETE FROM AppliUserT";
        String query4 = "ALTER TABLE AppliUserT MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query5 = "DELETE FROM Location";
        String query6 = "ALTER TABLE Location MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query7 = "DELETE FROM City";
        String query8 = "ALTER TABLE City MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        PreparedStatement statement = null;

        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query1);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query2);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query3);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query4);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query5);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query6);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query7);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query8);
            statement.executeQuery();

        } finally {
            if(statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Test
    @Order(4)
    public void testFind() throws SQLException {
        assertEquals(u1, unavailabilityDAO.find(1, 1), "Find the updated object.");
        assertEquals(u2, unavailabilityDAO.find(1, 2), "Find the unchanged object.");
        assertNull(unavailabilityDAO.find(2, 1), "There is no object with this ID.");
    }

    @Test
    @Order(1)
    public void testCreate() {
        assertDoesNotThrow(() -> {
            unavailabilityDAO.create(u1, i1);
        }, "Create a object in the database.");

        u1.setReason("Lazy");
        assertThrows(AlreadyExistsException.class, () -> {
            unavailabilityDAO.create(u1, i1);
        }, "This object already exists in the database with another reason.");

        assertDoesNotThrow(() -> {
            unavailabilityDAO.create(u2, i1);
        }, "Create another object in the database.");
    }

    @Test
    @Order(3)
    public void testUpdate() {
        u1.setReason("Lazy");
        assertDoesNotThrow(() -> {
            unavailabilityDAO.update(u1, i1);
        }, "The object has been updated.");

        assertThrows(NoSuchElementException.class, () -> {
            unavailabilityDAO.update(u3, i2);
        }, "There is no object with this Interpreter ID.");
    }

    @Test
    @Order(5)
    public void testDelete() {
        assertThrows(NoSuchElementException.class, () -> {
            unavailabilityDAO.delete(3, 3);
        }, "There are no objects with these IDs.");

        assertThrows(NoSuchElementException.class, () -> {
            unavailabilityDAO.delete(2, 1);
        }, "There are no objects with this combination of IDs.");

        assertDoesNotThrow(() -> {
            unavailabilityDAO.delete(1, 1);
        }, "The object has been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            unavailabilityDAO.delete(1, 1);
        }, "The object has already been removed from the database.");

        assertDoesNotThrow(() -> {
            unavailabilityDAO.delete(1, 2);
        }, "The object has been removed from the database.");
    }

    @Test
    @Order(2)
    public void testFindAll() throws SQLException {
        Set<ExceptionalUnavailability> unavailability = unavailabilityDAO.findAll();
        assertEquals(2, unavailability.size(), "There are two objects in the database.");
        u1.setReason("Sick");
        assertTrue(unavailability.contains(u1));
        assertTrue(unavailability.contains(u2));
    }
}