package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.models.JobSkill;
import org.junit.jupiter.api.*;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.NoSuchElementException;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DAOJobSkillTest {
    public static JobSkill j1;
    public static JobSkill j2;
    public static JobSkill j3;
    public final static DAOJobSkill jobSkillDAO = new DAOJobSkill();

    @BeforeAll
    public static void init() {
        DatabaseConnector.initialize("login", "password");
        j1 = new JobSkill(75, "Science");
        j2 = new JobSkill(1, "Français");
        j3 = new JobSkill(3, "Java");
    }

    @AfterAll
    public static void close() throws SQLException {
        reset();
        DatabaseConnector.closeInstance();
    }

    /*
     * Reset the tables used.
     */
    private static void reset() throws SQLException {
        String query1 = "DELETE FROM JobSkill";
        String query2 = "ALTER TABLE JobSkill MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        PreparedStatement statement = null;

        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query1);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query2);
            statement.executeQuery();
        } finally {
            if(statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Test
    @Order(4)
    public void testFind() throws SQLException {
        assertEquals(j3, jobSkillDAO.find(1), "Find the updated object.");
        assertEquals(j2, jobSkillDAO.find(2), "Find the unchanged object.");
        assertNull(jobSkillDAO.find(3), "There is no object with this ID.");
    }

    @Test
    @Order(1)
    public void testCreate() {
        assertDoesNotThrow(() -> {
            jobSkillDAO.create(j1);
        }, "Create a object in the database.");
        assertEquals(1, j1.getId(), "The ID must have been changed.");

        j1.setId(20);
        assertThrows(AlreadyExistsException.class, () -> {
            jobSkillDAO.create(j1);
        }, "This object already exists in the database with another ID.");

        assertDoesNotThrow(() -> {
            jobSkillDAO.create(j2);
        }, "Create another object in the database.");
        assertEquals(2, j2.getId(), "The ID must have been changed.");
    }

    @Test
    @Order(3)
    public void testUpdate() {
        assertThrows(NoSuchElementException.class, () -> {
            jobSkillDAO.update(j3);
        }, "There are no objects with this ID.");

        j3.setId(1);
        assertDoesNotThrow(() -> {
            jobSkillDAO.update(j3);
        }, "The object has been updated.");

        j3.setId(2);
        assertThrows(AlreadyExistsException.class, () -> {
            jobSkillDAO.update(j3);
        }, "This object already exists in the database with another ID.");
    }

    @Test
    @Order(5)
    public void testDelete() {
        assertDoesNotThrow(() -> {
            jobSkillDAO.delete(j2.getId());
        }, "The object has been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            jobSkillDAO.delete(j2.getId());
        }, "The object has already been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            jobSkillDAO.delete(50);
        }, "There is no object with this ID.");

        assertDoesNotThrow(() -> {
            jobSkillDAO.delete(1);
        }, "The object has been removed from the database.");
    }

    @Test
    @Order(2)
    public void testFindAll() throws SQLException {
        Set<JobSkill> jobSkills = jobSkillDAO.findAll();
        assertEquals(2, jobSkills.size(), "There are two objects in the database.");
        assertTrue(jobSkills.contains(j1));
        assertTrue(jobSkills.contains(j2));
    }
}