package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.models.City;
import be.hers.pi.comprendre_et_parler.models.Manager;
import be.hers.pi.comprendre_et_parler.models.Location;
import org.junit.jupiter.api.*;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.NoSuchElementException;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DAOManagerTest {
    public static Manager m1;
    public static Manager m2;
    public static Manager m3;
    public final static DAOManager managerDAO = new DAOManager();

    @BeforeAll
    public static void init() throws SQLException {
        DatabaseConnector.initialize("login", "password");
        City c1 = new City(1, "Bruxelles", 1000);
        new DAOCity().create(c1);
        Location l1 = new Location(1, "Bruxelles", c1, "Rue Neuve", "5", 0);
        new DAOLocation().create(l1);

        m1 = new Manager(75, "test1", "Toto", "Toto", LocalDate.now().minusYears(30),
                "1234", "toto@gmail.com", "123/45.67.89", 10, 120,
                "Auto", new HashSet<>(), new HashSet<>(), l1, new HashSet<>());
        m2 = new Manager(1, "r260001", "Tata", "Tata", LocalDate.now().minusYears(50),
                "9874", "tata@gmail.com", "987/65.41.32", 30, 450,
                "Auto", new HashSet<>(), new HashSet<>(), l1, new HashSet<>());
        m3 = new Manager(3, "b741985", "Alice", "Charpentier", LocalDate.now().minusYears(25),
                "yth794t8rg", "alice@gmail.com", "4865/75.98.24", 20, 300,
                "Vélo", new HashSet<>(), new HashSet<>(), l1, new HashSet<>());
    }

    @AfterAll
    public static void close() throws SQLException {
        resetAll();
        DatabaseConnector.closeInstance();
    }

    /*
     * Reset the tables used.
     */
    private static void resetAll() throws SQLException {
        String query1 = "DELETE FROM AppliUserT";
        String query2 = "ALTER TABLE AppliUserT MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query3 = "DELETE FROM Location";
        String query4 = "ALTER TABLE Location MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        String query5 = "DELETE FROM City";
        String query6 = "ALTER TABLE City MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1)";
        PreparedStatement statement = null;

        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query1);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query2);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query3);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query4);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query5);
            statement.executeQuery();
            statement = DatabaseConnector.getInstance().prepareStatement(query6);
            statement.executeQuery();

        } finally {
            if(statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Test
    @Order(4)
    public void testFind() throws SQLException {
        Manager m4 = managerDAO.find(1);
        assertEquals(m3, m4, "Find the updated object.");
        assertNotEquals(m3.getLogin(), m4.getLogin(), "The login must not have been updated.");
        assertEquals(m2, managerDAO.find(2), "Find the unchanged object.");
        assertNull(managerDAO.find(3), "There is no object with this ID.");
    }

    @Test
    @Order(1)
    public void testCreate() {
        assertDoesNotThrow(() -> {
            managerDAO.create(m1);
        }, "Create a object in the database.");
        assertEquals(1, m1.getId(), "The ID must have been changed.");
        assertEquals("r260001", m1.getLogin(), "The login must have been changed.");

        m1.setId(20);
        assertThrows(AlreadyExistsException.class, () -> {
            managerDAO.create(m1);
        }, "This object already exists in the database with another ID.");

        assertDoesNotThrow(() -> {
            managerDAO.create(m2);
        }, "Create another object in the database.");
        assertEquals(2, m2.getId(), "The ID must have been changed.");
        assertEquals("r260002", m2.getLogin(), "The login must have been changed.");
    }

    @Test
    @Order(3)
    public void testUpdate() {
        assertThrows(NoSuchElementException.class, () -> {
            managerDAO.update(m3);
        }, "There are no objects with this ID.");

        m3.setId(1);
        assertDoesNotThrow(() -> {
            managerDAO.update(m3);
        }, "The object has been updated.");

        m3.setId(2);
        assertThrows(AlreadyExistsException.class, () -> {
            managerDAO.update(m3);
        }, "This object already exists in the database with another ID.");
    }

    @Test
    @Order(5)
    public void testDelete() {
        assertDoesNotThrow(() -> {
            managerDAO.delete(m2.getId());
        }, "The object has been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            managerDAO.delete(m2.getId());
        }, "The object has already been removed from the database.");

        assertThrows(NoSuchElementException.class, () -> {
            managerDAO.delete(50);
        }, "There is no object with this ID.");

        assertDoesNotThrow(() -> {
            managerDAO.delete(1);
        }, "The object has been removed from the database.");
    }

    @Test
    @Order(2)
    public void testFindAll() throws SQLException {
        Set<Manager> managers = managerDAO.findAll();
        assertEquals(2, managers.size(), "There are two objects in the database.");
        assertTrue(managers.contains(m1));
        assertTrue(managers.contains(m2));
    }
}