DROP TABLE BeneficiaryMission;
DROP TABLE InterpreterMission;
DROP TABLE MissionLocation;
DROP TABLE Mission;
DROP TABLE JobSkillInterpreter;
DROP TABLE AcademicSkillInterpreter;
DROP TABLE AcademicSkill;
DROP TABLE JobSkill;
DROP TABLE Unavailability;
DROP TABLE Availability;
DROP TABLE TimeSlot;
DROP TABLE Beneficiary;
DROP TABLE Interpreter;
DROP TABLE AppliUser;
DROP TABLE Location;
DROP TABLE City;
DROP TABLE Transportation;
DROP TABLE Status;


CREATE TABLE Status (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE,
    hourQuota INTEGER NOT NULL
);

CREATE TABLE Transportation (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE City (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2 (50 CHAR) NOT NULL,
    postalCode NUMBER(4) NOT NULL
);

CREATE TABLE Location (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(50 CHAR),
    city INTEGER NOT NULL REFERENCES City(id) ON DELETE CASCADE,
    street VARCHAR2(50 CHAR) NOT NULL,
    streetNumber VARCHAR2(8 CHAR),
    box INTEGER
);

CREATE TABLE AppliUser (
    login VARCHAR2(8 CHAR) PRIMARY KEY,
    firstName VARCHAR2(25 CHAR) NOT NULL,
    lastName VARCHAR2(25 CHAR) NOT NULL,
    birthDate DATE NOT NULL,
    hashedPassword VARCHAR2(50 CHAR) NOT NULL,
    email VARCHAR2(50 CHAR) NOT NULL,
    phoneNumber VARCHAR2(25 CHAR)
);

CREATE TABLE Interpreter (
    login VARCHAR2(8 CHAR) PRIMARY KEY REFERENCES AppliUser(login) ON DELETE CASCADE,
    weekHourlyQuota INTEGER NOT NULL,
    yearHourlyQuota INTEGER NOT NULL,
    transportMode INTEGER NOT NULL REFERENCES Transportation(id),
    location INTEGER NOT NULL REFERENCES Location(id)
);

CREATE TABLE Beneficiary (
    login VARCHAR2(8 CHAR) PRIMARY KEY REFERENCES AppliUser(login) ON DELETE CASCADE,
    status INTEGER NOT NULL REFERENCES Status(id),
    referenceInterpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(login)
);

CREATE TABLE TimeSlot (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    startTime DATE NOT NULL,
    endTime DATE NOT NULL,
    day NUMBER(1)
);

CREATE TABLE Unavailability (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(login) ON DELETE CASCADE,
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    reason VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PKUnavailability PRIMARY KEY (interpreter, timeSlot)
);

CREATE TABLE Availability (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(login) ON DELETE CASCADE,
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    CONSTRAINT PKAvailability PRIMARY KEY (interpreter, timeSlot)
);

CREATE TABLE AcademicSkill (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE JobSkill (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(25 CHAR) UNIQUE
);

CREATE TABLE AcademicSkillInterpreter (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(login) ON DELETE CASCADE,
    skill INTEGER NOT NULL REFERENCES AcademicSkill(id) ON DELETE CASCADE,
    CONSTRAINT PKAcademicSkillInterpreter PRIMARY KEY (interpreter, skill)
);

CREATE TABLE JobSkillInterpreter (
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(login) ON DELETE CASCADE,
    skill INTEGER NOT NULL REFERENCES JobSkill(id) ON DELETE CASCADE,
    CONSTRAINT PKJobSkillInterpreter PRIMARY KEY (interpreter, skill)
);

CREATE TABLE Mission (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subject VARCHAR2(50 CHAR) NOT NULL,
    stateOfMission CHAR NOT NULL,
    commentary VARCHAR2(100 CHAR),
    timeSlot INTEGER NOT NULL REFERENCES TimeSlot(id),
    jobSkill INTEGER REFERENCES JobSkill(id),
    academicSkill INTEGER REFERENCES AcademicSkill(id)
);

CREATE TABLE MissionLocation (
    mission INTEGER NOT NULL REFERENCES Mission(id) ON DELETE CASCADE,
    location INTEGER NOT NULL REFERENCES Location(id),
    room VARCHAR2(25 CHAR),
    CONSTRAINT PKMissionLocation PRIMARY KEY (mission, location)
);

CREATE TABLE BeneficiaryMission (
    mission INTEGER NOT NULL REFERENCES Mission(id) ON DELETE CASCADE,
    beneficiary VARCHAR2(8 CHAR) NOT NULL REFERENCES Beneficiary(login) ON DELETE CASCADE,
    importance INTEGER NOT NULL,
    CONSTRAINT PKBeneficiaryMission PRIMARY KEY (mission, beneficiary)
);

CREATE TABLE InterpreterMission (
    mission INTEGER NOT NULL REFERENCES Mission(id) ON DELETE CASCADE,
    interpreter VARCHAR2(8 CHAR) NOT NULL REFERENCES Interpreter(login) ON DELETE CASCADE,
    CONSTRAINT PKInterpreterMission PRIMARY KEY (mission, interpreter)
);


ALTER TABLE Status ADD CONSTRAINT QuotaValue CHECK (hourQuota >= 0);

ALTER TABLE AppliUser ADD CONSTRAINT IDUser CHECK (REGEXP_LIKE(login,'^[ibr][0-9]{7}$')); 
ALTER TABLE AppliUser ADD CONSTRAINT PhoneNumberUser CHECK (phoneNumber IS NULL OR REGEXP_LIKE(phoneNumber,'^[0-9]+\/[0-9]+\.[0-9]+\.[0-9]+$'));
ALTER TABLE AppliUser ADD CONSTRAINT EmailUser CHECK (REGEXP_LIKE(email, '.+@.+\..+'));

ALTER TABLE Interpreter ADD CONSTRAINT IDInterpreter CHECK (REGEXP_LIKE(login,'^[ir][0-9]{7}$')); 
ALTER TABLE Interpreter ADD CONSTRAINT QuotaWeekValue CHECK (weekHourlyQuota >= 0);
ALTER TABLE Interpreter ADD CONSTRAINT QuotaYearValue CHECK (yearHourlyQuota >= 0);

ALTER TABLE Beneficiary ADD CONSTRAINT IDBeneficiary CHECK (REGEXP_LIKE(login,'^b[0-9]{7}$')); 

ALTER TABLE City ADD CONSTRAINT PostalCodeValue CHECK (postalCode > 999);

ALTER TABLE TimeSlot ADD CONSTRAINT DateOrder CHECK (startTime < endTime);
ALTER TABLE TimeSlot ADD CONSTRAINT TypeOfTimeSlot CHECK (day IS NULL OR day BETWEEN 0 AND 6);
ALTER TABLE TimeSlot ADD CONSTRAINT TimeSlotUnique UNIQUE (startTime, endTime, day);

ALTER TABLE Mission ADD CONSTRAINT StateOfMissionValue CHECK (stateOfMission IN ('A', 'R', 'D', 'H'));
ALTER TABLE Mission ADD CONSTRAINT SkillsNeeded CHECK ((jobSkill IS NULL AND academicSkill IS NULL) OR (jobSkill IS NOT NULL AND academicSkill IS NOT NULL));

commit;