package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.models.BaseTimeSlot;
import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.time.DayOfWeek;
import java.util.HashSet;
import java.util.Set;
import java.util.NoSuchElementException;

public class DAOBaseTimeSlot extends DAO<BaseTimeSlot> {

    protected static final String TABLE = "timeslot";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_START_TIME = "startTime";
    protected static final String FIELD_END_TIME = "endTime";
    protected static final String FIELD_DAY = "day";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public BaseTimeSlot find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NOT NULL AND " + FIELD_ID + " = ?";
        BaseTimeSlot ret = null;
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)){
            statement.setInt(1, id);
            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    ret = getResult(result);
                }
            }
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type BaseTimeSlot to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(BaseTimeSlot objectToInsert) throws AlreadyExistsException, SQLException {
        if (checkAlreadyExists(objectToInsert))
            throw new AlreadyExistsException("BaseTimeSlot" + objectToInsert.getDay() + " already exists");

        String query = "INSERT INTO %s(%s, %s, %s) VALUES(?, ?, ?)";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME, FIELD_DAY);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID})) {
            statement.setTime(1, Time.valueOf(objectToInsert.getStartTime()));
            statement.setTime(2, Time.valueOf(objectToInsert.getEndTime()));
            statement.setInt(3, objectToInsert.getDay().getValue());
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    objectToInsert.setId(generatedKeys.getInt(1));
                }
            }
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(BaseTimeSlot objectToUpdate) throws AlreadyExistsException, NoSuchElementException, SQLException {
        if (checkAlreadyExists(objectToUpdate))
            throw new AlreadyExistsException("BaseTimeSlot" + objectToUpdate.getDay() + " already exists");

        String query = "UPDATE %s SET %s = ?, %s = ?, %s = ? WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME, FIELD_DAY, FIELD_ID);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)){
            statement.setTime(1, Time.valueOf(objectToUpdate.getStartTime()));
            statement.setTime(2, Time.valueOf(objectToUpdate.getEndTime()));
            statement.setInt(3, objectToUpdate.getDay().getValue());
            statement.setInt(4, objectToUpdate.getId());
            if (statement.executeUpdate() == 0)
                throw new NoSuchElementException("Object of id " + objectToUpdate.getId() + "could not be found in database");
        }
    }

    /**
     * @param objectToDelete the object to delete in the database
     * @post the object matching every attribute of objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object matching every attribute of objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(BaseTimeSlot objectToDelete) throws NoSuchElementException, SQLException {
        BaseTimeSlot objectInDB = find(objectToDelete.getId());
        if (objectInDB == null)
            throw new NoSuchElementException("No object of id " + objectToDelete.getId() + " could be found in database");
        if (!objectInDB.equals(objectToDelete))
            throw new NoSuchElementException("An object of id " + objectToDelete.getId() + " was found in database, but its attributes do not match those of objectToDelete");

        String query = "DELETE FROM %s WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_ID);;
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            statement.setInt(1, objectToDelete.getId());
            statement.executeUpdate();
        }
    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty Set)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Set<BaseTimeSlot> findAll() throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NOT NULL";
        Set<BaseTimeSlot> ret = new HashSet<>();
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            try (ResultSet result = statement.executeQuery()) {
                while (result.next()) {
                    ret.add(getResult(result));
                }
            }
        }
        return ret;
    }

    @Override
    protected boolean checkAlreadyExists(BaseTimeSlot object) throws SQLException {
        String query = "SELECT * FROM %s WHERE %s IS NOT NULL AND %s = ? AND %s = ? AND %s = ?";
        query = String.format(query, TABLE, FIELD_DAY, FIELD_DAY, FIELD_START_TIME, FIELD_END_TIME);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)){
            statement.setInt(1, object.getDay().getValue());
            statement.setTime(2, Time.valueOf(object.getStartTime()));
            statement.setTime(3, Time.valueOf(object.getEndTime()));
            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    return true;
                }
            }
        }
        return false;
    }

    @Override
    protected BaseTimeSlot getResult(ResultSet result) throws SQLException {
        return new BaseTimeSlot(
                result.getInt(FIELD_ID),
                result.getTime(FIELD_START_TIME).toLocalTime(),
                result.getTime(FIELD_END_TIME).toLocalTime(),
                DayOfWeek.of(result.getInt(FIELD_DAY))
        );
    }

    public Set<BaseTimeSlot> findForInterpreter(int idInterpreter) throws SQLException, NoSuchElementException {
        return null;
    }
}