package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.models.BaseTimeSlot;
import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;

import java.sql.*;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.NoSuchElementException;

public class DAOBaseTimeSlot extends DAO<BaseTimeSlot> {

    protected static final String TABLE = "timeslot";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_START_TIME = "startDateTime";
    protected static final String FIELD_END_TIME = "endDateTime";
    protected static final String FIELD_DAY = "day";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public BaseTimeSlot find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NOT NULL AND " + FIELD_ID + " = ?";
        PreparedStatement statement = null;
        ResultSet result = null;
        BaseTimeSlot ret = null;

        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, id);
            result = statement.executeQuery();
            if (result.next()) {
                ret = getResult(result);
            }
        }
        finally {
            closeResultSet(result);
            closeStatement(statement);
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type BaseTimeSlot to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(BaseTimeSlot objectToInsert) throws AlreadyExistsException, SQLException {
        if (checkAlreadyExists(objectToInsert))
            throw new AlreadyExistsException("BaseTimeSlot" + objectToInsert.getDay() + " already exists");

        String query = "INSERT INTO %s(%s, %s, %s) VALUES(?, ?, ?)";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME, FIELD_DAY);
        PreparedStatement statement = null;
        ResultSet generatedKeys = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID});
            statement.setTimestamp(1, Timestamp.valueOf(LocalDateTime.of(objectToInsert.getStartDate(), objectToInsert.getStartTime())));
            statement.setTimestamp(2, Timestamp.valueOf(LocalDateTime.of(objectToInsert.getEndDate(), objectToInsert.getEndTime())));
            statement.setInt(3, objectToInsert.getDay().getValue());
            statement.executeUpdate();
            generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next())
                objectToInsert.setId(generatedKeys.getInt(1));
        }
        finally {
            closeResultSet(generatedKeys);
            closeStatement(statement);
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(BaseTimeSlot objectToUpdate) throws AlreadyExistsException, NoSuchElementException, SQLException {
        if (checkAlreadyExists(objectToUpdate))
            throw new AlreadyExistsException("This BaseTimeSlot already exists");

        String query = "UPDATE %s SET %s = ?, %s = ?, %s = ? WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME, FIELD_DAY, FIELD_ID);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setTimestamp(1, Timestamp.valueOf(LocalDateTime.of(objectToUpdate.getStartDate(), objectToUpdate.getStartTime())));
            statement.setTimestamp(2, Timestamp.valueOf(LocalDateTime.of(objectToUpdate.getEndDate(), objectToUpdate.getEndTime())));
            statement.setInt(3, objectToUpdate.getDay().getValue());
            statement.setInt(4, objectToUpdate.getId());
            if(statement.executeUpdate() == 0){
                throw new NoSuchElementException("Object of id " + objectToUpdate.getId() + "could not be found in database");
            }
        }
        finally {
            closeStatement(statement);
        }
    }

    /**
     * @param idObjectToDelete the ID of the object to delete in the database
     * @post the object ID matching objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object ID matching objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(int idObjectToDelete) throws NoSuchElementException, SQLException {
        String query = "DELETE FROM %s WHERE %s = ? AND %s IS NOT NULL";
        query = String.format(query, TABLE, FIELD_ID, FIELD_DAY);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, idObjectToDelete);
            if(statement.executeUpdate() == 0)
                throw new NoSuchElementException("BaseTimeSlot " + idObjectToDelete + " was not found in database");
        } finally {
            closeStatement(statement);
        }
    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty Set)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Set<BaseTimeSlot> findAll() throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NOT NULL";
        PreparedStatement statement = null;
        ResultSet result = null;
        Set<BaseTimeSlot> ret = new HashSet<>();
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            result = statement.executeQuery();
            while (result.next()) {
                ret.add(getResult(result));
            }
        }
        finally {
            closeResultSet(result);
            closeStatement(statement);
        }
        return ret;
    }

    @Override
    protected boolean checkAlreadyExists(BaseTimeSlot object) throws SQLException {
        String query = "SELECT 1 FROM %s WHERE %s IS NOT NULL AND %s = ? AND %s = ? AND %s = ?";
        query = String.format(query, TABLE, FIELD_DAY, FIELD_DAY, FIELD_START_TIME, FIELD_END_TIME);
        PreparedStatement statement = null;
        ResultSet result = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, object.getDay().getValue());
            statement.setTimestamp(2, Timestamp.valueOf(LocalDateTime.of(object.getStartDate(), object.getStartTime())));
            statement.setTimestamp(3, Timestamp.valueOf(LocalDateTime.of(object.getEndDate(), object.getEndTime())));
            result = statement.executeQuery();

            return result.next();
        }finally {
            closeResultSet(result);
            closeStatement(statement);
        }
    }

    @Override
    protected BaseTimeSlot getResult(ResultSet result) throws SQLException {
        return new BaseTimeSlot(
                result.getInt(FIELD_ID),
                result.getDate(FIELD_START_TIME).toLocalDate(),
                result.getDate(FIELD_END_TIME).toLocalDate(),
                result.getTime(FIELD_START_TIME).toLocalTime(),
                result.getTime(FIELD_END_TIME).toLocalTime(),
                DayOfWeek.of(result.getInt(FIELD_DAY))
        );
    }

    public Set<BaseTimeSlot> findForInterpreter(int idInterpreter) throws SQLException, NoSuchElementException {
        return new HashSet<>();
    }
}