package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.models.PunctualTimeSlot;
import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import java.util.NoSuchElementException;

public class DAOPunctualTimeSlot extends DAO<PunctualTimeSlot> {

    protected static final String TABLE = "timeslot";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_START_TIME = "startDateTime";
    protected static final String FIELD_END_TIME = "endDateTime";
    protected static final String FIELD_DAY = "day";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public PunctualTimeSlot find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NULL AND " + FIELD_ID + " = ?";
        PreparedStatement statement = null;
        ResultSet result = null;
        PunctualTimeSlot ret = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, id);
            result = statement.executeQuery();
            if (result.next()) {
                ret = getResult(result);
            }
        }
        finally {
            closeResultSet(result);
            closeStatement(statement);
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type PunctualTimeSlot to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(PunctualTimeSlot objectToInsert) throws AlreadyExistsException, SQLException {
        if (checkAlreadyExists(objectToInsert))
            throw new AlreadyExistsException("PunctualTimeSlot" + objectToInsert.getStartDate() + " to " + objectToInsert.getEndDate() +  " already exists");

        String query = "INSERT INTO %s(%s, %s) VALUES(?, ?)";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME);
        PreparedStatement statement = null;
        ResultSet generatedKeys = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID});
            statement.setTimestamp(1, Timestamp.valueOf(objectToInsert.getStartDate()));
            statement.setTimestamp(2, Timestamp.valueOf(objectToInsert.getEndDate()));
            statement.executeUpdate();

            generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next())
                objectToInsert.setId(generatedKeys.getInt(1));
        }
        finally {
            closeResultSet(generatedKeys);
            closeStatement(statement);
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(PunctualTimeSlot objectToUpdate) throws AlreadyExistsException, NoSuchElementException, SQLException {
        if (checkAlreadyExists(objectToUpdate))
            throw new AlreadyExistsException("PunctualTimeSlot" + objectToUpdate.getStartDate() + " to " + objectToUpdate.getEndDate() +  " already exists");

        String query = "UPDATE %s SET %s = ?, %s = ? WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME, FIELD_ID);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setTimestamp(1, Timestamp.valueOf(objectToUpdate.getStartDate()));
            statement.setTimestamp(2, Timestamp.valueOf(objectToUpdate.getEndDate()));
            statement.setInt(3, objectToUpdate.getId());
            if(statement.executeUpdate() == 0){
                throw new NoSuchElementException("Object of id " + objectToUpdate.getId() + "could not be found in database");
            }
        }
        finally {
            closeStatement(statement);
        }
    }

    /**
     * @param idObjectToDelete the object to delete in the database
     * @post the object ID matching objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object ID matching objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(int idObjectToDelete) throws NoSuchElementException, SQLException {
        String query = "DELETE FROM %s WHERE %s = ? AND %s IS NULL";
        query = String.format(query, TABLE, FIELD_ID, FIELD_DAY);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, idObjectToDelete);

            if(statement.executeUpdate() == 0)
                throw new NoSuchElementException("PunctualTimeSlot " + idObjectToDelete + " was not found in database");
        } finally {
            closeStatement(statement);
        }
    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty Set)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Set<PunctualTimeSlot> findAll() throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NULL";
        PreparedStatement statement = null;
        ResultSet result = null;
        Set<PunctualTimeSlot> ret = new HashSet<>();
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            result = statement.executeQuery();
            while (result.next())
                ret.add(getResult(result));
        }
        finally {
            closeResultSet(result);
            closeStatement(statement);
        }
        return ret;
    }

    @Override
    protected boolean checkAlreadyExists(PunctualTimeSlot object) throws SQLException {
        String query = String.format("SELECT 1 FROM %s WHERE %s IS NULL AND %s = ? AND %s = ?",
                TABLE, FIELD_DAY, FIELD_START_TIME, FIELD_END_TIME);
        PreparedStatement statement = null;
        ResultSet result = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setTimestamp(1, Timestamp.valueOf(object.getStartDate()));
            statement.setTimestamp(2, Timestamp.valueOf(object.getEndDate()));

            result = statement.executeQuery();
            return result.next();
        }finally {
            closeResultSet(result);
            closeStatement(statement);
        }
    }

    @Override
    protected PunctualTimeSlot getResult(ResultSet result) throws SQLException {
        return new PunctualTimeSlot(
                result.getInt(FIELD_ID),
                result.getTimestamp(FIELD_START_TIME).toLocalDateTime(),
                result.getTimestamp(FIELD_END_TIME).toLocalDateTime()
        );
    }
}