package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.models.PunctualTimeSlot;
import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;

import java.time.LocalDateTime;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;

public class DAOPunctualTimeSlot implements DAO<PunctualTimeSlot> {

    protected static final String TABLE = "timeslot";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_START_TIME = "startTime";
    protected static final String FIELD_END_TIME = "endTime";
    protected static final String FIELD_DAY = "day";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public PunctualTimeSlot find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NULL AND " + FIELD_ID + " = ?";
        PunctualTimeSlot ret = null;
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query);) {
            statement.setInt(1, id);
            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    ret = new PunctualTimeSlot(
                            result.getInt(FIELD_ID),
                            result.getTime(FIELD_START_TIME).toLocalTime(),
                            result.getTime(FIELD_END_TIME).toLocalTime(),
                            result.getDate(FIELD_START_TIME).toLocalDate()
                    );
                }
            }
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type PunctualTimeSlot to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(PunctualTimeSlot objectToInsert) throws AlreadyExistsException, SQLException {
        // Manage invalid states
        String query = "SELECT * FROM %s WHERE %s IS NULL AND %s = ? AND %s = ?";
        query = String.format(query, TABLE, FIELD_DAY, FIELD_START_TIME, FIELD_END_TIME);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)){
            LocalDateTime beginning = LocalDateTime.of(objectToInsert.getDate(), objectToInsert.getStartTime());
            LocalDateTime end = LocalDateTime.of(objectToInsert.getDate(), objectToInsert.getEndTime());
            statement.setTimestamp(1, Timestamp.valueOf(beginning));
            statement.setTimestamp(2, Timestamp.valueOf(end));
            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    throw new AlreadyExistsException("Object already exists in database");
                }
            }
        }

        // Attempt insertion
        query = "INSERT INTO %s(%s, %s) VALUES(?, ?)";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID})) {
            LocalDateTime beginning = LocalDateTime.of(objectToInsert.getDate(), objectToInsert.getStartTime());
            LocalDateTime end = LocalDateTime.of(objectToInsert.getDate(), objectToInsert.getEndTime());
            statement.setTimestamp(1, Timestamp.valueOf(beginning));
            statement.setTimestamp(2, Timestamp.valueOf(end));
            statement.executeUpdate();

            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                objectToInsert.setId(generatedKeys.getInt(1));
            }
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(PunctualTimeSlot objectToUpdate) throws AlreadyExistsException, NoSuchElementException, SQLException {
        // Manage invalid states
        List<PunctualTimeSlot> allLines = findAll();
        if (allLines == null)
            throw new NoSuchElementException("No object of type BaseTimeSlot could be found in database");
        boolean idFound = false;
        for(PunctualTimeSlot line : allLines) {
            if (line.getId() == objectToUpdate.getId()) {
                idFound = true;
            }
            if (line.getStartTime().equals(objectToUpdate.getStartTime())
                    && line.getEndTime().equals(objectToUpdate.getEndTime())
                    && line.getDate().equals(objectToUpdate.getDate())) {
                if (line.getId() == objectToUpdate.getId()) {
                    return; // DB is up to date, nothing to do.
                } else {
                    throw new AlreadyExistsException("Object of id " + objectToUpdate.getId() + "already exists at id " + line.getId());
                }
            }
        }
        if (!idFound)
            throw new NoSuchElementException("Object of id " + objectToUpdate.getId() + "could not be found in database");

        // Attempt update
        String query = "UPDATE %s SET %s = ?, %s = ? WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME, FIELD_ID);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)){
            LocalDateTime beginning = LocalDateTime.of(objectToUpdate.getDate(), objectToUpdate.getStartTime());
            LocalDateTime end = LocalDateTime.of(objectToUpdate.getDate(), objectToUpdate.getEndTime());
            statement.setTimestamp(1, Timestamp.valueOf(beginning));
            statement.setTimestamp(2, Timestamp.valueOf(end));
            statement.setInt(3, objectToUpdate.getId());
            statement.executeUpdate();
        }
    }

    /**
     * @param objectToDelete the object to delete in the database
     * @post the object matching every attribute of objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object matching every attribute of objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(PunctualTimeSlot objectToDelete) throws NoSuchElementException, SQLException {
        PunctualTimeSlot objectInDB = find(objectToDelete.getId());
        if (objectInDB == null)
            throw new NoSuchElementException("No object of id " + objectToDelete.getId() + " could be found in database");
        if (!objectInDB.equals(objectToDelete))
            throw new NoSuchElementException("An object of id " + objectToDelete.getId() + " was found in database, but its attributes do not match those of objectToDelete");

        String query = "DELETE FROM %s WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_ID);;
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            statement.setInt(1, objectToDelete.getId());
            statement.executeUpdate();
        }
    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty list)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public List<PunctualTimeSlot> findAll() throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NULL";
        List<PunctualTimeSlot> ret = new ArrayList<>();
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            try (ResultSet result = statement.executeQuery()) {
                while (result.next()) {
                    ret.add(new PunctualTimeSlot(
                            result.getInt(FIELD_ID),
                            result.getTime(FIELD_START_TIME).toLocalTime(),
                            result.getTime(FIELD_END_TIME).toLocalTime(),
                            result.getDate(FIELD_START_TIME).toLocalDate()
                    ));
                }
            }
        }
        return ret;
    }
}