package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.models.BaseTimeSlot;
import be.hers.pi.comprendre_et_parler.models.PunctualTimeSlot;
import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.exceptions.ConnectionException;
import be.hers.pi.comprendre_et_parler.exceptions.DuplicatePrimaryKeyException;
import be.hers.pi.comprendre_et_parler.models.Status;

import java.sql.*;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.util.List;
import java.util.NoSuchElementException;

public class DAOPunctualTimeSlot implements DAO<PunctualTimeSlot> {

    // TODO : fix resultSets cleanup

    protected static final String TABLE = "timeslot";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_START_TIME = "startTime";
    protected static final String FIELD_END_TIME = "endTime";
    protected static final String FIELD_DAY = "day";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public PunctualTimeSlot find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_DAY + " IS NULL AND " + FIELD_ID + " = ?";
        PreparedStatement statement = null;
        ResultSet result = null;
        PunctualTimeSlot ret = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, id);
            result = statement.executeQuery();
            if (result.next()) {
                ret = new PunctualTimeSlot(
                        result.getInt(FIELD_ID),
                        result.getTime(FIELD_START_TIME).toLocalTime(),
                        result.getTime(FIELD_END_TIME).toLocalTime(),
                        result.getDate(FIELD_START_TIME).toLocalDate()
                );
            }
        }
        finally {
            if (statement != null)
                statement.close();
            if (result != null)
                result.close();
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type PunctualTimeSlot to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(PunctualTimeSlot objectToInsert) throws AlreadyExistsException, SQLException {
        // Manage invalid states
        List<PunctualTimeSlot> allLines = findAll();
        if (allLines.contains(objectToInsert))
            throw new AlreadyExistsException("Object already exists in database");

        // Attempt insertion
        String query = "INSERT INTO %s(%s, %s) VALUES(?, ?)";
        query = String.format(query, TABLE, FIELD_START_TIME, FIELD_END_TIME);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID});
            LocalDateTime beginning = LocalDateTime.of(objectToInsert.getDate(), objectToInsert.getStartTime());
            LocalDateTime end = LocalDateTime.of(objectToInsert.getDate(), objectToInsert.getEndTime());
            statement.setTimestamp(1, Timestamp.valueOf(beginning));
            statement.setTimestamp(2, Timestamp.valueOf(end));
            statement.executeUpdate();

            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                objectToInsert.setId(generatedKeys.getInt(1));
            }
        }
        finally {
            if (statement != null) {
                statement.close();
            }
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(PunctualTimeSlot objectToUpdate) throws AlreadyExistsException, NoSuchElementException, SQLException {

    }

    /**
     * @param objectToDelete the object to delete in the database
     * @post the object matching every attribute of objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object matching every attribute of objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(PunctualTimeSlot objectToDelete) throws NoSuchElementException, SQLException {

    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty list)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public List<PunctualTimeSlot> findAll() throws SQLException {
        return List.of();
    }
}