package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.models.Status;

import java.util.HashSet;
import java.util.Set;
import java.util.NoSuchElementException;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class DAOStatus implements DAO<Status> {
    protected static final String TABLE = "status";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_DESIGNATION = "designation";
    protected static final String FIELD_HOUR_QUOTA = "hourquota";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Status find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_ID + " = ?";
        Status ret = null;
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            statement.setInt(1, id);
            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    ret = new Status(
                            result.getInt(FIELD_ID),
                            result.getString(FIELD_DESIGNATION),
                            result.getInt(FIELD_HOUR_QUOTA)
                    );
                }
            }
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type Status to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(Status objectToInsert) throws AlreadyExistsException, SQLException {
        // Manage invalid states
        int duplicateId = findDuplicate(objectToInsert);
        if (duplicateId >= 0)
            throw new AlreadyExistsException("Object already exists in database at id " + duplicateId);

        // Attempt insertion
        String query = "INSERT INTO %s(%s, %s) VALUES(?, ?)";
        query = String.format(query, TABLE, FIELD_DESIGNATION, FIELD_HOUR_QUOTA);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID})) {
            statement.setString(1, objectToInsert.getDesignation());
            statement.setInt(2, objectToInsert.getHourQuota());
            statement.executeUpdate();
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    objectToInsert.setId(generatedKeys.getInt(1));
                }
            }
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(Status objectToUpdate) throws NoSuchElementException, AlreadyExistsException, SQLException {
        // Manage invalid states
        int duplicateId = findDuplicate(objectToUpdate);
        if (duplicateId >= 0)
            throw new AlreadyExistsException("Object of id " + objectToUpdate.getId() + "already exists at id " + duplicateId);

        // Attempt update
        String query = "UPDATE %s SET %s = ?, %s = ? WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_DESIGNATION, FIELD_HOUR_QUOTA, FIELD_ID);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            statement.setString(1, objectToUpdate.getDesignation());
            statement.setInt(2, objectToUpdate.getHourQuota());
            statement.setInt(3, objectToUpdate.getId());
            if (statement.executeUpdate() == 0)
                throw new NoSuchElementException("Object of id " + objectToUpdate.getId() + "could not be found in database");
        }
    }

    /**
     * @param objectToDelete the object to delete in the database
     * @post the object matching every attribute of objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object matching every attribute of objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(Status objectToDelete) throws NoSuchElementException, SQLException {
        Status objectInDB = find(objectToDelete.getId());
        if (objectInDB == null)
            throw new NoSuchElementException("No object of id " + objectToDelete.getId() + " could be found in database");
        if (!objectInDB.equals(objectToDelete))
            throw new NoSuchElementException("An object of id " + objectToDelete.getId() + " was found in database, but its attributes do not match those of objectToDelete");

        String query = "DELETE FROM %s WHERE %s = ? AND %s = ? AND %s = ?";
        query = String.format(query, TABLE, FIELD_ID, FIELD_DESIGNATION, FIELD_HOUR_QUOTA);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            statement.setInt(1, objectToDelete.getId());
            statement.setString(2, objectToDelete.getDesignation());
            statement.setInt(3, objectToDelete.getHourQuota());
            statement.executeUpdate();
        }
    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty Set)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Set<Status> findAll() throws SQLException {
        String query = "SELECT * FROM " + TABLE;
        Set<Status> ret = new HashSet<>();
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query)) {
            try (ResultSet result = statement.executeQuery()) {
                while (result.next()) {
                    ret.add(new Status(
                            result.getInt(FIELD_ID),
                            result.getString(FIELD_DESIGNATION),
                            result.getInt(FIELD_HOUR_QUOTA)
                    ));
                }
            }
        }
        return ret;
    }

    /**
     *
     * @param obj the object to find in database
     * @return the id of an identical object in database, or -1 if none was found
     * @throws SQLException if a database error occured
     */
    private int findDuplicate(Status obj) throws SQLException {
        String query = "SELECT * FROM %s WHERE %s = ? AND %s = ? ";
        query = String.format(query, TABLE, FIELD_DESIGNATION, FIELD_HOUR_QUOTA);
        try (PreparedStatement statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID})) {
            statement.setString(1, obj.getDesignation());
            statement.setInt(2, obj.getHourQuota());
            statement.executeUpdate();
            try (ResultSet result = statement.executeQuery()) {
                if (result.next()) {
                    return result.getInt(FIELD_ID);
                }
            }
        }
        return -1;
    }
}