package be.hers.pi.comprendre_et_parler.DAOs;

import be.hers.pi.comprendre_et_parler.exceptions.AlreadyExistsException;
import be.hers.pi.comprendre_et_parler.models.Status;

import java.util.HashSet;
import java.util.Set;
import java.util.NoSuchElementException;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class DAOStatus extends DAO<Status> {
    protected static final String TABLE = "status";
    protected static final String FIELD_ID = "id";
    protected static final String FIELD_DESIGNATION = "designation";
    protected static final String FIELD_HOUR_QUOTA = "hourquota";

    /**
     * @param id the primary key of the object to find in database
     * @return the object identified by id in database, or null if none was present
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Status find(int id) throws SQLException {
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_ID + " = ?";
        PreparedStatement statement = null;
        ResultSet result = null;
        Status ret = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, id);
            result = statement.executeQuery();
            if (result.next()) {
                ret = getResult(result);
            }
        }
        finally {
            closeResultSet(result);
            closeStatement(statement);
        }
        return ret;
    }

    /**
     * @param objectToInsert an object of type Status to add to the database
     * @post objectToInsert has been added to the database, and the change was commited. objectToInsert's id field has been changed to the one auto-generated by the database
     * @throws AlreadyExistsException if objectToInsert is already present in database
     * @throws SQLException if the insertion failed for any other reason
     */
    @Override
    public void create(Status objectToInsert) throws AlreadyExistsException, SQLException {
        if (checkAlreadyExists(objectToInsert))
            throw new AlreadyExistsException("Status" + objectToInsert.getDesignation() +  " already exists");

        String query = "INSERT INTO %s(%s, %s) VALUES(?, ?)";
        query = String.format(query, TABLE, FIELD_DESIGNATION, FIELD_HOUR_QUOTA);
        PreparedStatement statement = null;
        ResultSet generatedKeys = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query, new String[]{FIELD_ID});
            statement.setString(1, objectToInsert.getDesignation());
            statement.setInt(2, objectToInsert.getHourQuota());
            statement.executeUpdate();

            generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next())
                objectToInsert.setId(generatedKeys.getInt(1));
        }
        finally {
            closeResultSet(generatedKeys);
            closeStatement(statement);
        }
    }

    /**
     * @param objectToUpdate the object to edit in the database
     * @post the line referenced by objectToUpdate's id field has been updated with objectToUpdate's attributes, and the change was commited
     * @throws NoSuchElementException if no object matching objectToUpdate's id was present in the database
     * @throws AlreadyExistsException if an object with a different id but otherwise identical fields already exists in database
     * @throws SQLException if the update failed for any other reason
     */
    @Override
    public void update(Status objectToUpdate) throws NoSuchElementException, AlreadyExistsException, SQLException {
        if (checkAlreadyExists(objectToUpdate))
            throw new AlreadyExistsException("Status " + objectToUpdate.getDesignation() + " already exists");

        String query = "UPDATE %s SET %s = ?, %s = ? WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_DESIGNATION, FIELD_HOUR_QUOTA, FIELD_ID);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setString(1, objectToUpdate.getDesignation());
            statement.setInt(2, objectToUpdate.getHourQuota());
            statement.setInt(3, objectToUpdate.getId());
            if(statement.executeUpdate() == 0)
                throw new NoSuchElementException("Object of id " + objectToUpdate.getId() + "could not be found in database");
        }
        finally {
            closeStatement(statement);
        }
    }

    /**
     * @param idObjectToDelete the object to delete in the database
     * @post the object ID matching objectToDelete has been deleted from the database, and the change was commited
     * @throws NoSuchElementException if no object ID matching objectToDelete was present in the database
     * @throws SQLException if the deletion failed for any other reason
     */
    @Override
    public void delete(int idObjectToDelete) throws NoSuchElementException, SQLException {
        String query = "DELETE FROM %s WHERE %s = ?";
        query = String.format(query, TABLE, FIELD_ID);
        PreparedStatement statement = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setInt(1, idObjectToDelete);
            if(statement.executeUpdate() == 0)
                throw new NoSuchElementException("Status " + idObjectToDelete + " was not found in database");
        } finally {
            closeStatement(statement);
        }
    }

    /**
     * @return every object of the corresponding type present in database (possibly an empty Set)
     * @throws SQLException if the database could not be reached
     */
    @Override
    public Set<Status> findAll() throws SQLException {
        String query = "SELECT * FROM " + TABLE;
        PreparedStatement statement = null;
        ResultSet result = null;
        Set<Status> ret = new HashSet<Status>();
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            result = statement.executeQuery();
            while (result.next())
                ret.add(getResult(result));
        }
        finally {
            closeResultSet(result);
            closeStatement(statement);
        }
        return ret;
    }

    @Override
    protected boolean checkAlreadyExists(Status object) throws SQLException {
        String query = "SELECT 1 FROM %s WHERE %s = ? AND %s = ? ";
        query = String.format(query, TABLE, FIELD_DESIGNATION, FIELD_HOUR_QUOTA);
        PreparedStatement statement = null;
        ResultSet result = null;
        try {
            statement = DatabaseConnector.getInstance().prepareStatement(query);
            statement.setString(1, object.getDesignation());
            statement.setInt(2, object.getHourQuota());

            result = statement.executeQuery();
            return result.next();
        }finally {
            closeResultSet(result);
            closeStatement(statement);
        }
    }

    @Override
    protected Status getResult(ResultSet result) throws SQLException {
        return new Status(
                result.getInt(FIELD_ID),
                result.getString(FIELD_DESIGNATION),
                result.getInt(FIELD_HOUR_QUOTA)
        );
    }
}